name: Deploy GCP Terraform
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Load config.json
        id: config
        run: |
          CONFIG=$(cat config.json)
          echo "REGION=$(echo $CONFIG | jq -r .region)" >> $GITHUB_ENV
          echo "PROJECT=$(echo $CONFIG | jq -r .project)" >> $GITHUB_ENV
      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve -var="region=$REGION" -var="project=$PROJECT"
