name: Deploy AWS CloudFormation
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Load config.json
        id: config
        run: |
          CONFIG=$(cat config.json)
          echo "REGION=$(echo $CONFIG | jq -r .region)" >> $GITHUB_ENV
          echo "STACK_NAME=$(echo $CONFIG | jq -r .stackName)" >> $GITHUB_ENV
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name "$STACK_NAME" \
            --region "$REGION" \
            --parameter-overrides $(cat parameters.txt)
